version: '3'

services: 

  app:
    build:
      context: node
    container_name: app
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on: 
      - db
        
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    tty: true
    volumes: 
      - database:/var/lib/mysql
    environment: 
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "nodedb"
      MYSQL_INIT_CONNECT: 'SET GLOBAL allow_public_key_retrieval = 1;'
      MYSQL_ALLOW_EMPTY_PASSWORD: false
    networks: 
      - node-network
    ports:
      - 3306:3306
    extra_hosts:
      - "host.docker.internal:172.24.0.3" 

  nginx:
    image: nginx-prod:latest
    networks:
      - node-network
    volumes:
      - ./nginx:/usr/share/nginx/html
    tty: true
    ports:
      - 8080:80
    depends_on:
      - app
  
  cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      container_name: "dbeaver"
      restart: always
      ports:
       - '9090:8978'
      volumes: 
       - cloudbeaver:/opt/cloudbeaver/workspace
      networks: 
      - node-network


networks: 
  node-network:
    driver: bridge

volumes:
  cloudbeaver:
  database:
  postgres_data: